#!/bin/bash

###########################################################
#
# Clone repo:
#  git clone git@github.com:smeghead/atnd.git attendance
#
# Edit your .bashrc
#  export ATND_TOOL=/home/fukata/usr/local/attendance
#  export PATH=$PATH:$ATND_TOOL
#
# Reload .bashrc:
#  source ~/.bashrc
#
# Usage:
#  atnd [-l num] [-d ids] msg
#
#   OPTIONS:
#    -l display latest messages. default num is 5.
#    -d delete messages. separated comma ID.
#
###########################################################

# Basic Settings
BASEDIR=$(dirname $0)
PGNAME=$(basename $0)

# Database
DB_NAME="$BASEDIR/$PGNAME.db"
CMD_CONNECT="sqlite3 $DB_NAME"

function show_help() {
	usage="Usage: 
  atnd [-l num] [-d ids] msg 

OPTIONS: 
  -l display latest messages. 
  -d delete messages. separated comma ID.
"
	echo $usage
	exit 1
}

# Utility
function exec_sql() {
	local sql=${1?"SQL is required."}
	echo "$sql" | $CMD_CONNECT
}

function create_atnd() {
	local msg=${1?"Message is required."}
	msg=${msg/\'/\'\'}
	local sql="INSERT INTO logs (msg, created_at) VALUES ('$msg', julianday('now'));"

	exec_sql "$sql"
}

function list_atnd() {
	local num=${1?"NUM is required."}
	local sql="SELECT id, datetime(created_at, 'localtime'), msg FROM logs ORDER BY created_at DESC LIMIT $num;"

	exec_sql "$sql"
}

function delete_atnd() {
	local ids=${1?"ID is required."}
	ORG_IFS=$IFS
	IFS=,
	for id in $ids; do
		IFS=$ORG_IFS
		local sql="DELETE FROM logs WHERE id=$id;"
		exec_sql "$sql"
	done
}

# Initialize Database
if [ ! -e $DB_NAME ]; then
	exec_sql "CREATE TABLE logs ( \
		id INTEGER PRIMARY KEY, \
		msg TEXT NOT NULL, \
		created_at REAL NOT NULL);"
fi

# Parse Options
LIST_MODE=0
LIST_NUM=0
DELETE_MODE=0
DELETE_ID=0
while getopts "l:d:" OPTION; do
	case $OPTION in
		l)
			LIST_MODE=1
			LIST_NUM=$OPTARG
			;;
		d)
			DELETE_MODE=1
			DELETE_ID=$OPTARG
			;;
		*)
			;;
	esac
done
shift $(($OPTIND - 1))

if [ "x$LIST_MODE" == "x1" ]; then
	list_atnd $LIST_NUM
elif [ "x$DELETE_MODE" == "x1" ]; then
	delete_atnd "$DELETE_ID"
elif [ "x$1" != "x" ]; then
	create_atnd "$1"
else
	show_help
fi
